GET http://localhost:2900/api/employers?sort=companyName&order=asc&page=1

###
GET http://localhost:2900/api/employers?sector=Government&sort=companyName&order=asc&page=1

###
GET http://localhost:2900/api/employers?sector=Private&sort=companyName&order=asc&page=1

###
GET http://localhost:2900/api/employers/search?term=IsTRy

###
GET http://localhost:2900/api/employers/62266005813800af4efd9ebe