GET http://localhost:2900/api/employers?sort=companyName&order=asc&page=1

###
GET http://localhost:2900/api/employers?sector=Government&sort=companyName&order=asc&page=1

###
GET http://localhost:2900/api/employers?sector=Private&sort=companyName&order=asc&page=1
# `http://localhost:4000/employers?sector=Private&_sort=name&_order=asc&_page=${page}`