POST http://localhost:2900/api/jobs/623210c8665f86576787e972/create
Content-Type: application/json

{
    "jobType": "Full-time",
    "postedBy": "623210c8665f86576787e972",
    "title": "Administrative Officer",
    "dueDate": "2022-03-30",
    "salary": 7800
}


###

POST http://localhost:2900/api/jobs/62594df4cd4534524e899389/create
Content-Type: application/json

{
    "title":"",
    "jobType": "",
    "noOfPositions":"",
    "location":"",
    "dueDate":"",
    "salary":"",
    "minQualification":"",
    "jobCategory":"",
    "description":"",
    "responsibilities":[],
    "criteria":[]
}

###


GET http://localhost:2900/api/jobs?jobCategory=Information Technology&jobType=Full-time&salaryRange=10000-14999

###
GET http://localhost:2900/api/jobs?empId=62321057341ed8fb740ac2ba
